python twitterapp.py gather "coronavirus" --consumer_key=wq9vn7JxoZ75yZv236HgQPpiv --consumer_secret=Z1RZlqxXI2cAobSKepQjEa7vf0IboBiH5SXeTiFRQdmopHqyaw
python twitterapp.py gather "coronavirus" --consumer_key=wq9vn7JxoZ75yZv236HgQPpiv --consumer_secret=Z1RZlqxXI2cAobSKepQjEa7vf0IboBiH5SXeTiFRQdmopHqyaw
python twitterapp.py gather "coronavirus" --consumer_key=wq9vn7JxoZ75yZv236HgQPpiv --consumer_secret=Z1RZlqxXI2cAobSKepQjEa7vf0IboBiH5SXeTiFRQdmopHqyaw
